# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install -y graphviz
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run all Jupyter notebooks
      run: |
        cd en/
        papermill installation.ipynb tmp.ipynb
        rm tmp.ipynb
        cd ../ ; cd practical1/
        papermill practical1.ipynb tmp.ipynb
        rm tmp.ipynb
        cd ../ ; cd practical2/
        papermill practical2.ipynb tmp.ipynb
        rm tmp.ipynb
        cd ../ ; cd practical3/
        papermill practical3.ipynb tmp.ipynb
        rm tmp.ipynb
        cd ../ ; cd practical4/
        papermill practical4.ipynb tmp.ipynb
        rm tmp.ipynb
        cd ../ ; cd ./examples/
        papermill Examples-Visualization.ipynb tmp.ipynb
        papermill Examples.ipynb tmp.ipynb
        papermill decisiontree.ipynb tmp.ipynb
        papermill mlp.ipynb tmp.ipynb
        papermill perceptron.ipynb tmp.ipynb
        papermill rfc.ipynb tmp.ipynb
        papermill svm.ipynb tmp.ipynb
        papermill recommendation.ipynb tmp.ipynb
        rm tmp.ipynb

